# Generated by Django 3.1 on 2020-12-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0007_auto_20201202_0340'),
        ('courses', '0004_auto_20201202_0340'),
        ('trainings', '0003_training_sidebar_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=500, null=True, verbose_name='Текст')),
                ('reference', models.CharField(choices=[('news_reference', 'Новости'), ('training_reference', 'Тренинги'), ('course_reference', 'Курсы')], help_text='Выберите раздел, к которому будет привязан слайд', max_length=30, verbose_name='Привязка слайда к разделу')),
                ('button', models.CharField(choices=[(None, 'Без дополнительной кнопки'), ('main_page/call_button.html', 'Кнопка "Позвонить"'), ('main_page/contact_button.html', 'Ссылка на страницу "Контакты"')], default='no_button', max_length=100, verbose_name='Дополнительная кнопка')),
                ('course_reference', models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Привязка к записи')),
                ('news_reference', models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.article', verbose_name='Привязка к записи')),
                ('training_reference', models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainings.training', verbose_name='Привязка к записи')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
