# Generated by Django 3.1 on 2020-12-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_training_sidebar_size'),
        ('news', '0007_auto_20201202_0340'),
        ('courses', '0004_auto_20201202_0340'),
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='button',
            field=models.CharField(choices=[(None, 'Без дополнительной кнопки'), ('call', 'Кнопка "Позвонить"'), ('contact', 'Ссылка на страницу "Контакты"')], default='no_button', max_length=100, verbose_name='Дополнительная кнопка'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='course_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='news_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.article', verbose_name='Выберите новость'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='reference',
            field=models.CharField(choices=[('news_reference', 'Новости'), ('training_reference', 'Тренинги'), ('course_reference', 'Курсы')], help_text='Выберите раздел, к которому будет привязан слайд', max_length=30, verbose_name='Привязка к разделу'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='training_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainings.training', verbose_name='Выберите тренинг'),
        ),
    ]
