# Generated by Django 3.1 on 2020-12-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20201206_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='reference',
            field=models.CharField(choices=[('news_reference', 'Новости'), ('training_reference', 'Тренинги'), ('course_reference', 'Курсы')], default='news_reference', help_text='Выберите раздел, к которому будет привязан слайд', max_length=30, verbose_name='Привязка к разделу'),
        ),
    ]
