# Generated by Django 3.1 on 2020-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20201206_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='button',
            field=models.CharField(blank=True, choices=[(None, 'Без дополнительной кнопки'), ('call', 'Кнопка "Позвонить"'), ('contact', 'Ссылка на страницу "Контакты"')], default=None, max_length=100, null=True, verbose_name='Дополнительная кнопка'),
        ),
    ]
