# Generated by Django 3.1 on 2020-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20201206_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'ordering': ['sorting'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AddField(
            model_name='mainslider',
            name='sorting',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения в слайдере'),
        ),
    ]
