# Generated by Django 3.1 on 2020-12-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201202_0340'),
        ('news', '0007_auto_20201202_0340'),
        ('trainings', '0003_training_sidebar_size'),
        ('main_page', '0005_auto_20201206_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondarySlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Неактивные слайды не будут отображены в слайдере', verbose_name='Активно')),
                ('reference', models.CharField(choices=[('news_reference', 'Новости'), ('training_reference', 'Тренинги'), ('course_reference', 'Курсы')], default='news_reference', help_text='Выберите раздел, к которому будет привязан слайд', max_length=30, verbose_name='Привязка к разделу')),
                ('sorting', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения в слайдере')),
                ('course_reference', models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Выберите курс')),
                ('news_reference', models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.article', verbose_name='Выберите новость')),
                ('training_reference', models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainings.training', verbose_name='Выберите тренинг')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды (Второй слайдер)',
                'ordering': ['sorting'],
            },
        ),
        migrations.DeleteModel(
            name='InlineSlider',
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'ordering': ['sorting'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды (Главный слайдер)'},
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='text',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=250, null=True, verbose_name='Текст'),
        ),
    ]
