# Generated by Django 3.1 on 2020-12-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201202_0340'),
        ('news', '0007_auto_20201202_0340'),
        ('trainings', '0003_training_sidebar_size'),
        ('main_page', '0007_auto_20201206_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleblock',
            options={'verbose_name': 'Одиночный блок', 'verbose_name_plural': 'Одиночный блок'},
        ),
        migrations.CreateModel(
            name='StaticBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст')),
                ('reference', models.CharField(choices=[('news_reference', 'Новости'), ('training_reference', 'Тренинги'), ('course_reference', 'Курсы')], default='news_reference', help_text='Выберите раздел, к которому будет привязан слайд', max_length=30, verbose_name='Привязка к разделу')),
                ('course_reference', models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Выберите курс')),
                ('news_reference', models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.article', verbose_name='Выберите новость')),
                ('training_reference', models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainings.training', verbose_name='Выберите тренинг')),
            ],
            options={
                'verbose_name': 'Статичный блок',
                'verbose_name_plural': 'Статичные блоки',
            },
        ),
    ]
