# Generated by Django 3.1 on 2020-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20201206_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticblock',
            name='active',
            field=models.BooleanField(default=True, help_text='Неактивные слайды не будут отображены в слайдере', verbose_name='Активно'),
        ),
    ]
