# Generated by Django 3.1 on 2020-12-06 14:53

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_staticblock_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('status', models.CharField(max_length=70, verbose_name='Статус (ученик, сотрудник, ...)')),
                ('active', models.BooleanField(default=True, help_text='Неактивные слайды не будут отображены в слайдере', verbose_name='Активно')),
                ('rating', models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='Оценка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Аватар')),
                ('avatar_size', image_cropping.fields.ImageRatioField('image', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения для аватара')),
                ('text', models.CharField(max_length=750, verbose_name='Содержание комментария')),
                ('sorting', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения в слайдере')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['sorting'],
            },
        ),
    ]
