# Generated by Django 3.1 on 2020-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avatar_size',
        ),
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], default='ru', max_length=20, verbose_name='Язык комментария'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5, verbose_name='Оценка'),
        ),
    ]
