# Generated by Django 3.1.4 on 2020-12-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201202_0340'),
        ('news', '0007_auto_20201202_0340'),
        ('trainings', '0003_training_sidebar_size'),
        ('main_page', '0011_auto_20201206_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleblock',
            name='course_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='singleblock',
            name='news_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.article', verbose_name='Выберите новость'),
        ),
        migrations.AlterField(
            model_name='singleblock',
            name='reference',
            field=models.CharField(choices=[('news_reference', 'Новости'), ('training_reference', 'Тренинги'), ('course_reference', 'Курсы')], default='news_reference', help_text='Выберите раздел, к которому будет привязан данный блок', max_length=30, verbose_name='Привязка к разделу'),
        ),
        migrations.AlterField(
            model_name='singleblock',
            name='training_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainings.training', verbose_name='Выберите тренинг'),
        ),
        migrations.AlterField(
            model_name='staticblock',
            name='course_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='staticblock',
            name='news_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.article', verbose_name='Выберите новость'),
        ),
        migrations.AlterField(
            model_name='staticblock',
            name='reference',
            field=models.CharField(choices=[('news_reference', 'Новости'), ('training_reference', 'Тренинги'), ('course_reference', 'Курсы')], default='news_reference', help_text='Выберите раздел, к которому будет привязан данный блок', max_length=30, verbose_name='Привязка к разделу'),
        ),
        migrations.AlterField(
            model_name='staticblock',
            name='training_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainings.training', verbose_name='Выберите тренинг'),
        ),
    ]
