# Generated by Django 3.1.4 on 2020-12-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20201208_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='text_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=250, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='text_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=250, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='secondaryslider',
            name='text_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='secondaryslider',
            name='text_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='secondaryslider',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='secondaryslider',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='singleblock',
            name='text_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='singleblock',
            name='text_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='singleblock',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='singleblock',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='staticblock',
            name='text_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='staticblock',
            name='text_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать текст выбранной записи', max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='staticblock',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='staticblock',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать заголовок выбранной записи', max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
