# Generated by Django 3.1.4 on 2020-12-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201221_2001'),
        ('trainings', '0006_auto_20201221_2001'),
        ('courses', '0005_auto_20201221_2001'),
        ('main_page', '0013_auto_20201221_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'ordering': ['sorting'], 'verbose_name': 'Элемент слайдера', 'verbose_name_plural': 'Блок #1 (Первый слайдер)'},
        ),
        migrations.AlterModelOptions(
            name='secondaryslider',
            options={'ordering': ['sorting'], 'verbose_name': 'Элемент слайдера', 'verbose_name_plural': 'Блок #2 (Второй слайдер)'},
        ),
        migrations.AlterModelOptions(
            name='singleblock',
            options={'verbose_name': 'Одиночный блок', 'verbose_name_plural': 'Блок #3 (Одиночный блок)'},
        ),
        migrations.AlterModelOptions(
            name='staticblock',
            options={'verbose_name': 'Статичный блок', 'verbose_name_plural': 'Блок #4 (Статичные блоки)'},
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='course_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='news_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.article', verbose_name='Выберите новость'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='training_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.training', verbose_name='Выберите тренинг'),
        ),
        migrations.AlterField(
            model_name='secondaryslider',
            name='course_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='secondaryslider',
            name='news_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.article', verbose_name='Выберите новость'),
        ),
        migrations.AlterField(
            model_name='secondaryslider',
            name='training_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.training', verbose_name='Выберите тренинг'),
        ),
        migrations.AlterField(
            model_name='singleblock',
            name='course_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='singleblock',
            name='news_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.article', verbose_name='Выберите новость'),
        ),
        migrations.AlterField(
            model_name='singleblock',
            name='training_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.training', verbose_name='Выберите тренинг'),
        ),
        migrations.AlterField(
            model_name='staticblock',
            name='course_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите курс, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='staticblock',
            name='news_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите статью, на которую будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.article', verbose_name='Выберите новость'),
        ),
        migrations.AlterField(
            model_name='staticblock',
            name='training_reference',
            field=models.ForeignKey(blank=True, help_text='Выберите тренинг, на который будет ссылаться данный блок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.training', verbose_name='Выберите тренинг'),
        ),
    ]
