# Generated by Django 3.1 on 2020-11-20 12:29

import autoslug.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='URL категории')),
                ('active', models.BooleanField(default=True, help_text='Неактивные категории не будут отображаться в списке категорий', verbose_name='Активно')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать информацию из шаблона news.html', max_length=1000, null=True, verbose_name='Описание (мета-тег)')),
            ],
            options={
                'verbose_name': 'Категория статей',
                'verbose_name_plural': 'Категории статей',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок статьи')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('status', models.CharField(choices=[('editing', 'Редактирование'), ('pending', 'Ожидание'), ('published', 'Опубликовано')], default='editing', help_text='Отображаться будут только статьи с состоянием "Выпущено"', max_length=30, verbose_name='Состояние статьи')),
                ('short_text', models.CharField(blank=True, help_text='Информация для превью статьи (необязательно)', max_length=500, null=True, verbose_name='Краткая информация о статье')),
                ('image', models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='articles/', verbose_name='Изображение статьи')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать первые 250 знаков статьи', max_length=1000, null=True, verbose_name='Описание (мета-тег)')),
                ('thumbnail_size', image_cropping.fields.ImageRatioField('image', '288x276', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью')),
                ('article_size', image_cropping.fields.ImageRatioField('image', '0x0', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для статьи')),
                ('associations', models.ManyToManyField(blank=True, to='news.ArticleCategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
