# Generated by Django 3.1 on 2020-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать первые 500 знаков статьи', max_length=1000, null=True, verbose_name='Описание (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_text',
            field=models.CharField(blank=True, help_text='Информация для превью статьи (необязательно). Оставьте поле пустым, чтобы использовать первые 500 знаков статьи', max_length=500, null=True, verbose_name='Краткая информация о статье'),
        ),
    ]
