# Generated by Django 3.1 on 2020-11-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201121_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='associations',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='active',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.articlecategory', verbose_name='Категории'),
        ),
    ]
