# Generated by Django 3.1 on 2020-10-31 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_n', models.IntegerField(verbose_name='Номер договора')),
                ('certificate_n', models.IntegerField(verbose_name='Номер сертификата')),
                ('inn', models.IntegerField(validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator], verbose_name='ИНН студента')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('date_received', models.DateField(verbose_name='Дата получения договора')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['date_received'],
            },
        ),
    ]
