# Generated by Django 3.1.4 on 2020-12-07 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_n',
            field=models.CharField(max_length=20, validators=[django.core.validators.DecimalValidator], verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='inn',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator], verbose_name='ИНН студента'),
        ),
    ]
