# Generated by Django 3.1.4 on 2020-12-13 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20201208_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='inn',
            field=models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator], verbose_name='ИНН студента'),
        ),
    ]
