# Generated by Django 3.1.4 on 2021-12-28 13:11

import django.core.validators
from django.db import migrations, models
import tools.utils


class Migration(migrations.Migration):

    dependencies = [
        ('small_purchase', '0003_auto_20211227_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpayer',
            name='pinfl',
            field=models.CharField(help_text=tools.utils.pinfl_help_text, max_length=30, validators=[django.core.validators.validate_integer], verbose_name='ПИНФЛ'),
        ),
        migrations.AlterField(
            model_name='smallpurchaserecord',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во наименований товаров'),
        ),
    ]
