# Generated by Django 3.1.4 on 2023-01-25 03:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tools.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('small_purchase', '0004_auto_20211228_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallpurchaserecord',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('active', True), ('app_label', 'trainings'), ('model', 'Training')), models.Q(('active', True), ('app_label', 'services'), ('model', 'Service')), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='small_purchases', to='contenttypes.contenttype', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='smallpurchaserecord',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualpayer',
            name='pinfl',
            field=models.CharField(help_text=tools.utils.pinfl_help_text, max_length=30, validators=[django.core.validators.validate_integer], verbose_name='ПИНФЛ'),
        ),
        migrations.AlterField(
            model_name='smallpurchaserecord',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во наименований услуг'),
        ),
    ]
