# Generated by Django 3.1.4 on 2023-01-25 03:17
from django.db import migrations


def forwards(apps, schema_editor):
    """ Copy id from old field `service_id` to a new generic one (`object_id`)
     and set content type to Service model (as there were no such other related models before) """
    SmallPurchaseRecord = apps.get_model('small_purchase', 'SmallPurchaseRecord')

    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.get_for_model(SmallPurchaseRecord)

    for item in SmallPurchaseRecord.objects.all():
        item.object_id = item.service_id
        item.content_type = content_type
        item.save()


def backwards(apps, schema_editor):
    """ Reversing: Copy id new generic field `object_id` to the old one `service_id` """
    SmallPurchaseRecord = apps.get_model('small_purchase', 'SmallPurchaseRecord')

    for item in SmallPurchaseRecord.objects.all():
        item.service_id = item.object_id
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('small_purchase', '0005_add_generic_fk'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
    ]
