# Generated by Django 3.1.4 on 2023-01-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_purchase', '0006_move_values_to_generic_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallpurchaserecord',
            name='service',
        ),
    ]
