# Generated by Django 3.1.2 on 2020-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='URL страницы')),
                ('name', models.CharField(max_length=200, verbose_name='Имя страницы (из urls.py')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('meta_description', models.CharField(blank=True, help_text='Необязательно. Используется для CEO.', max_length=1000, null=True, verbose_name='Описание (мета-тег)')),
                ('meta_description_ru', models.CharField(blank=True, help_text='Необязательно. Используется для CEO.', max_length=1000, null=True, verbose_name='Описание (мета-тег)')),
                ('meta_description_uz', models.CharField(blank=True, help_text='Необязательно. Используется для CEO.', max_length=1000, null=True, verbose_name='Описание (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Необязательно. Используется для CEO.', max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)')),
                ('meta_keywords_ru', models.CharField(blank=True, help_text='Необязательно. Используется для CEO.', max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)')),
                ('meta_keywords_uz', models.CharField(blank=True, help_text='Необязательно. Используется для CEO.', max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)')),
                ('meta_robots', models.CharField(blank=True, help_text='Необязательно. Используется для CEO.', max_length=500, null=True, verbose_name='Robots (мета-тег)')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
