# Generated by Django 3.1 on 2020-10-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.page', verbose_name='Следует после'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для SEO.', max_length=1000, null=True, verbose_name='Описание (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для SEO.', max_length=1000, null=True, verbose_name='Описание (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_uz',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для SEO.', max_length=1000, null=True, verbose_name='Описание (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для SEO.', max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для SEO.', max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для SEO.', max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_robots',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для SEO.', max_length=500, null=True, verbose_name='Robots (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя страницы (из urls.py)'),
        ),
    ]
