# Generated by Django 3.1 on 2020-10-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201026_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.page', verbose_name='Следует после'),
        ),
    ]
