# Generated by Django 3.1 on 2020-10-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20201026_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL страницы'),
        ),
    ]
