# Generated by Django 3.1 on 2020-10-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_page_show_in_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sorting'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='sorting',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения в меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя страницы (из urls.py)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.page', verbose_name='Следует после (в хлебных крошках)'),
        ),
    ]
