# Generated by Django 3.1 on 2020-10-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20201026_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь к шаблону'),
        ),
    ]
