# Generated by Django 3.1 on 2020-12-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_page_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_name_ru',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать заголовок страницы', max_length=200, null=True, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_name_uz',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать заголовок страницы', max_length=200, null=True, verbose_name='Название в меню'),
        ),
    ]
