# Generated by Django 3.1 on 2020-12-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20201202_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('key', models.CharField(editable=False, max_length=200, verbose_name='Ключ')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Статическая информация',
                'verbose_name_plural': 'Статическая информация',
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sorting'], 'verbose_name': 'Настройки страницы', 'verbose_name_plural': 'Настройки страниц'},
        ),
    ]
