# Generated by Django 3.1 on 2020-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_auto_20201203_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinformation',
            name='key',
            field=models.CharField(max_length=200, verbose_name='Ключ'),
        ),
    ]
