# Generated by Django 3.1 on 2020-11-30 06:33

import autoslug.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(blank=True, help_text='Информация для превью (необязательно). Оставьте поле пустым, чтобы использовать первые 500 знаков статьи', max_length=500, null=True, verbose_name='Описание')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать первые 250 знаков статьи', max_length=250, null=True, verbose_name='Описание (мета-тег)')),
                ('text', models.TextField(verbose_name='Контент')),
                ('title', models.CharField(max_length=500, verbose_name='Название курса')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL курса')),
                ('active', models.BooleanField(default=True, help_text='Неактивные курсы не будут отображаться на страницах сайта', verbose_name='Активно')),
                ('image', models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='', verbose_name='Изображение')),
                ('sidebar_size', image_cropping.fields.ImageRatioField('image', '140x140', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью (сайдбар)')),
                ('thumbnail_size', image_cropping.fields.ImageRatioField('image', '1024x576', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью (страница курса)')),
                ('price', models.IntegerField(verbose_name='Цена на курс')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
