# Generated by Django 3.1 on 2020-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sorting'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='sorting',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения в списках'),
        ),
    ]
