# Generated by Django 3.1 on 2020-11-30 08:18

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201130_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_size',
            field=image_cropping.fields.ImageRatioField('image', '512x288', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью (страница курса)'),
        ),
    ]
