# Generated by Django 3.1 on 2020-12-01 22:40

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201130_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, help_text='Неактивные курсы не будут отображаться на сайте', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sidebar_size',
            field=image_cropping.fields.ImageRatioField('image', '140x140', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения для превью (сайдбар)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail_size',
            field=image_cropping.fields.ImageRatioField('image', '512x288', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения для превью (список курсов)'),
        ),
    ]
