# Generated by Django 3.1 on 2020-12-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='sidebar_size',
        ),
    ]
