# Generated by Django 3.1 on 2020-12-03 12:25

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_remove_training_sidebar_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='sidebar_size',
            field=image_cropping.fields.ImageRatioField('image', '140x140', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения для превью (сайдбар)'),
        ),
    ]
