# Generated by Django 3.1.4 on 2020-12-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_training_sidebar_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='price',
            field=models.IntegerField(default=20000000, verbose_name='Цена на курс'),
            preserve_default=False,
        ),
    ]
