# Generated by Django 3.1.4 on 2020-12-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_training_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='date_arranged',
        ),
        migrations.RemoveField(
            model_name='training',
            name='location',
        ),
    ]
